name: MDC Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2
  
  dev:
    needs: build  # O estágio de desenvolvimento depende do estágio de build
    runs-on: ubuntu-latest

    steps:
      - name: Fase de Desenvolvimento
        run: echo "Executando Deploy de DEV"
  
  qa:
    needs: build # O estágio de qualidade depende de estágio de build
    runs-on: ubuntu-latest

    stpes:
      - name: Fase de Qualidade
        run: echo "Executando Deploy de QA"
  
  hml:
    needs:
      - dev # O estágio de homologação depende dos estágios de desenvolvimento e qualidade
      - qa
    runs-on: ubuntu-latest

    steps:
      - name: Fase de Homologação
        run: echo "Executando Deploy de HML"
  
  prd:
    needs: hml # O estágio de produção depende do estágio de homologação
    runs-on: ubuntu-latest

    steps:
      - name: Fase de Produção
        run: echo "Executando Deploy de PRD"
